# Generated by Django 4.1.7 on 2023-02-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_brand', models.CharField(max_length=100)),
                ('prod_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=30)),
                ('ingredients', models.CharField(max_length=200)),
                ('product_url', models.CharField(max_length=300)),
            ],
        ),
    ]
