# Generated by Django 4.1.7 on 2023-02-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredibly_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=60)),
                ('use', models.CharField(max_length=200)),
                ('allergen_flag', models.CharField(max_length=3)),
                ('health_flag', models.CharField(max_length=3)),
            ],
        ),
    ]
